//MapActions
export const RICHIESTA_PERMESSI = 'RICHIESTA_PERMESSI';
export const PERMESSO_NEGATO = 'PERMESSO_NEGATO';
export const RECUPERA_NEGOZI = 'RECUPERA_NEGOZI';
export const CAMBIA_REGIONE_MAPPA = 'CAMBIA_REGIONE_MAPPA';
export const NUOVO_NEGOZIO_CARICATO = 'NUOVO_NEGOZIO_CARICATO';
export const NEGOZIO_MODIFICATO = 'NEGOZIO_MODIFICATO';
export const NEGOZIO_ELIMINATO = 'NEGOZIO_ELIMINATO';
export const AGGIORNA_ALERT = 'AGGIORNA_ALERT';

//AuthActions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const SET_ERROR = 'SET_ERROR';

//NotifyActions
export const TOKEN_TAKEN = 'TOKEN_TAKEN';
export const SEND_NOTIFY = 'SEND_NOTIFY';

//CalloutActions
export const TOGGLE_FOLLOW = 'TOGGLE_FOLLOW';
export const VISUALIZZA_MARKER = 'VISUALIZZA_MARKER';
export const AGGIORNA_MARKER = 'AGGIORNA_MARKER';
